// Discovery Inbox helpers (built 2026-09-27). Load on /brand/discovery with the Inbox tab open:
//   eval(await fetch('http://127.0.0.1:8765/discovery-helpers.js').then(r => r.text()))
// Needs chat-helpers.js (robotic) and roster-scan.js (inboxNames) loaded first.
// Send flow per applicant: await dGo(name, firstName, text, expectTail) -> 'armed' -> real Return key -> dVer()
// Accept: const c = await findCard(name); check c.prog / c.country; c.btn.click()
window.LONG_OK = true;
window.reqOf = (b) => { const k = Object.keys(b).find(k => k.startsWith('__reactFiber')); let f = b[k]; for (let d = 0; d < 8 && f; d++) { if (f.memoizedProps && f.memoizedProps.request) return f.memoizedProps; f = f.return; } };
window.pageBtns = () => [...document.querySelectorAll('main button')].filter(x => /^\d+$/.test(x.innerText.trim()));
window.goPage = async (pg) => { const b = pageBtns().find(x => x.innerText.trim() === pg); if (!b) return false; const first = inboxNames()[0]; b.click(); for (let w = 0; w < 20; w++) { await new Promise(r => setTimeout(r, 400)); if (inboxNames()[0] !== first) break; } return true; };
window.eachPage = async (fn) => { await goPage('1'); for (let p = 1; p <= 8; p++) { if (p > 1 && !(await goPage(String(p)))) break; const r = await fn(p); if (r) return r; } return null; };
window.cardFor = (name) => { for (const b of [...document.querySelectorAll('button')].filter(x => /^\s*Approve\s*$/i.test(x.textContent || ''))) { const p = reqOf(b); const c = p && p.request.creator; if (c && (c.firstName + ' ' + (c.lastName || '')).trim() === name) return { btn: b, prog: p.request.program.name, cid: p.request.creatorId, country: (c.creatorProfile || {}).country, msg: (p.request.message || '').slice(0, 300), tt: (c.creatorProfile || {}).tiktokUrl, ig: (c.creatorProfile || {}).instagramUrl, sample: p.request.sampleCreative && p.request.sampleCreative.url }; } return null; };
window.findCard = async (name) => cardFor(name) || await eachPage(() => cardFor(name));
window.profDlg = () => [...document.querySelectorAll('[role=dialog]')].find(d => /Creator profile/.test(d.innerText));
window.closeAll = async () => { for (let i = 0; i < 3; i++) { if (!profDlg()) return; document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true })); await new Promise(z => setTimeout(z, 700)); } };
window.nameSpan = (name) => [...document.querySelectorAll('main *')].find(e => e.children.length === 0 && e.textContent.trim() === name);
window.dOpen = async (name) => { await closeAll(); const sp = nameSpan(name) || await eachPage(() => nameSpan(name)); if (!sp) return 'not found'; sp.click(); await new Promise(z => setTimeout(z, 2000)); const oc = document.querySelector('button[aria-label="Open chat"]'); if (!oc) return 'no open chat'; oc.click(); await new Promise(z => setTimeout(z, 2500)); let d = profDlg(); if (!d) return 'no dlg'; let tail = d.innerText.replace(/\s+/g, ' ').slice(-400); if (tail.length < 80) { await new Promise(z => setTimeout(z, 2500)); d = profDlg(); tail = d.innerText.replace(/\s+/g, ' ').slice(-400); } return { tail }; };
window.dArmD = (first, text) => { const d = profDlg(); if (!d) return 'no dlg'; const rb = robotic(text); if (rb.length) return 'ROBOTIC ' + rb; const t = d.querySelector('textarea'); if (!t || t.placeholder.indexOf('Message ' + first) !== 0) return 'wrong chat: ' + (t && t.placeholder); if (t.value) return 'not empty'; if (d.innerText.includes(text.slice(0, 50))) return 'ALREADY SENT'; Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype, 'value').set.call(t, text); t.dispatchEvent(new Event('input', { bubbles: true })); const b = [...d.querySelectorAll('button')].filter(x => /send/i.test((x.getAttribute('aria-label') || '') + x.innerText)).pop(); if (!b) return 'no send btn'; b.focus(); window._last = text; return 'armed'; };
window.dVer = () => { const d = profDlg(); return { count: d.innerText.split(_last.slice(0, 50)).length - 1, composer: d.querySelector('textarea').value.length }; };
window.dGo = async (name, first, text, expectTail) => { const o = await dOpen(name); if (typeof o === 'string') { document.activeElement.blur(); return name + ': ' + o; } if (expectTail && !o.tail.includes(expectTail)) { document.activeElement.blur(); return name + ': TAIL CHANGED: ' + o.tail.slice(-200); } const a = dArmD(first, text); if (a !== 'armed') { const t = profDlg() && profDlg().querySelector('textarea'); if (t && t.value === text) { Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype, 'value').set.call(t, ''); t.dispatchEvent(new Event('input', { bubbles: true })); } document.activeElement.blur(); return name + ': ' + a; } return 'armed'; };
// Attachment video URL from an applicant's chat: open with dOpen, then await attVideo()
window.attVideo = async () => { const img = [...profDlg().querySelectorAll('img')].find(i => /attachments/.test(decodeURIComponent(i.src))); if (!img) return null; (img.closest('button,a,[role=button]') || img).click(); await new Promise(z => setTimeout(z, 2500)); const v = [...document.querySelectorAll('video')].map(v => v.currentSrc || v.src || (v.querySelector('source') || {}).src).filter(Boolean); document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true })); await new Promise(z => setTimeout(z, 800)); return v.map(u => u.split('?')[0]); };
'discovery helpers loaded';
